apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../testbed
  - iiv-clustersecretstore.yaml
patches:
  - path: patch-backend-iiv.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: aods-backend
    path: patch-backend-iiv-json.yaml
