apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: smoke-20260401-1448
  namespace: shared
spec:
  host: smoke-20260401-1448.shared.svc.cluster.local
  subsets:
    - name: stable
      labels:
        app.kubernetes.io/name: smoke-20260401-1448
