apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smoke-20260401-1448
  namespace: shared
  annotations:
    aods.io/iiv-path: secret/aods/apps/shared/smoke-20260401-1448/shared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aods-iiv
    kind: ClusterSecretStore
  target:
    name: smoke-20260401-1448-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: aods/apps/shared/smoke-20260401-1448/shared
