apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: smoke-20260401-1448
  namespace: shared
spec:
  hosts:
    - smoke-20260401-1448.shared.svc.cluster.local
  http:
    - route:
        - destination:
            host: smoke-20260401-1448.shared.svc.cluster.local
            subset: stable
