apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aods-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/Aolda/aolda-orchestration-deployment-system.git
    targetRevision: main
    path: deploy/aods-system/overlays/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: aods-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
